/*
 * THIS CLASS WAS GENERATED BY AdamiWorks MirrorDB v.0.0.1-SNAPSHOT
 * Creation time: 2015-03-24 19:38:56
 */

package com.adamiworks.finanza.entity;

import com.adamiworks.mirrordb.annotations.Column;
import com.adamiworks.mirrordb.annotations.Table;

/**
 * TABLE COMMENTS: Informações sobre cada operação realizada no sistema.
 */
@Table(name="transacao", schema="public")
public class Transacao {

	@Column(name="id_transacao", primaryKey=true)
	private Integer idTransacao;

	@Column(name="id_campus", primaryKey=false)
	private Integer idCampus;

	@Column(name="id_pessoa", primaryKey=false)
	private Integer idPessoa;

	@Column(name="data_hora", primaryKey=false)
	private java.util.Date dataHora;

	/**
	 * COLUMN COMMENTS: Descrição gravada pelo sistema sobre a operação
	 */
	@Column(name="descricao", primaryKey=false)
	private String descricao;

	public Integer getIdTransacao() {
		return this.idTransacao;
	}

	public void setIdTransacao(Integer idTransacao) {
		this.idTransacao = idTransacao;
	}

	public Integer getIdCampus() {
		return this.idCampus;
	}

	public void setIdCampus(Integer idCampus) {
		this.idCampus = idCampus;
	}

	public Integer getIdPessoa() {
		return this.idPessoa;
	}

	public void setIdPessoa(Integer idPessoa) {
		this.idPessoa = idPessoa;
	}

	public java.util.Date getDataHora() {
		return this.dataHora;
	}

	public void setDataHora(java.util.Date dataHora) {
		this.dataHora = dataHora;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}